#!/bin/bash
#SBATCH -p dgx2q                   # partition (GPU queue)
#SBATCH -N 1                       # number of nodes
#SBATCH -n 4                       # number of cores
#SBATCH -w g001                    # DGX-2 node
#SBATCH --gres=gpu:4               # number of V100's
#SBATCH --mem 10G                  # memory pool for all cores
#SBATCH -t 0-00:10                 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out  # STDOUT
#SBATCH -e slurm.%N.%j.err  # STDERR

ulimit -s 10240
module load slurm 
module load openmpi/4.0.1

# Check how many gpu's your job got
#nvidia-smi

# Run job
cd /home/martinls/src/ShallowWaterGPU
mpirun --mca btl_openib_if_include mlx5_0 --mca btl_openib_warn_no_device_params_found 0 /home/martinls/miniconda3/envs/ShallowWaterGPU_HPC/bin/python3 mpiTesting.py

